### ISSUE TITLE
Minor rendering problem in BSplines section

### ISSUE THREAD

**Issue by hpmachining** [Pomax/BezierInfo-2#101]
In the section **How to compute a B-Spline curve: some maths** the subscripts for P<sub>0</sub> and P<sub>n - 1</sub> are not rendering properly. Replacing the backticks with code tags fixes it.
[bspline.txt](https://github.com/Pomax/BezierInfo-2/files/950077/bspline.txt)

**Comment by Pomax** [comment]
This is a pretty "git with github" project, could I ask you to hit the edit button for https://github.com/Pomax/BezierInfo-2/blob/master/components/sections/bsplines/content.en-GB.md with those changes and then have github file the PR for you?

**Comment by hpmachining** [comment]
OK, I think I did what you asked. I agree that the single backticks should have worked, but it appears to be treating inside the backticks as a quoted string. But then again, I know very little about markdown and HTML, so my assumption may be off base.

**Comment by Pomax** [comment]
Weighing the options, I've filed https://github.com/Pomax/BezierInfo-2/issues/104 to address the issue in terms of the markdown conversion, rather than adding HTML tags to the markdown (since the idea of markdown is "don't add syntax unless it's absolutely necessary", which should not be the case here... something odd is going on)
