### ISSUE TITLE
Bernstein polynomial definition

### ISSUE THREAD

**Issue by mashabow** [Pomax/BezierInfo-2#105]
Translating section 10, I found that the term "Bernstein polynomial" is used without definition.

**Comment by Pomax** [comment]
It's a reference to the Preface, which talks about the fact that Beziers are contensiously named because it's work by Bezier, and de Casteljau, but at its core can even be said to just be polynomials investigated by Bernstein. 

That said, let's make that a wikipedia link: `[Bernstein polynomial](https://en.wikipedia.org/wiki/Bernstein_polynomial)`

**Comment by mashabow** [comment]
Nice! I'll add the Japanese translation later.
