### ISSUE TITLE
Cardano JavaScript implementation has minor issues

### ISSUE THREAD

**Issue by isonno** [Pomax/BezierInfo-2#126]
The JavaScript implementation of Cardano's algorithm in section 16 has several minor issues:

- The functions `sqrt`, `cos` and `acos` are missing the `Math.` prefix.
- `pi` Should be `Math.PI`
- The cube root function is defined as `crt` but called as `cuberoot` (I'd side with changing the definition).

A corrected version is [here](https://jsfiddle.net/saccade/k1bs3tf4/).

**Comment by isonno** [comment]
Also, should note the bugs that occur if the cubic and quadratic terms are zero. See Pomax/bezierjs#85

**Comment by Pomax** [comment]
I'm pretty sure I didn't write it as copy-pastable JS code, the `Math` prefix is missing because I *always* bind most math functions globally. I have never run into a situation where having `sin`, `cos`, etc. namespaced makes things better. The same goes for `pi` (and frequently `tau` and `qs` for quarter circle).

If the code defines the cuberoot function as `crt` but calls it as `cuberoot`, that's definitely something to fix, but let's not fix the `Math` namespacing.

**Comment by Pomax** [comment]
fixed up the text, and bumped the bezierjs dependency to 2.2.6, which has the fix to the actual code itself.
