### ISSUE TITLE
Example of parametric circle shows incorrect graph

### ISSUE THREAD

**Issue by ammo888** [Pomax/BezierInfo-2#145]
`x=sin(t), y=cos(t); t=[0,5]` does not produce the graph shown in the primer in section 3.
This is what the graph should look like:
[desmos](https://www.desmos.com/calculator/kkik2e7ihx)

**Comment by Pomax** [comment]
Just because you're used to the coordinate system using (-+, ++, +-, --) for top-left, top-right, bottom-right, and bottom-left from your maths education, does not mean that everything uses coordinate system. Computer graphics almost universally use the (--, +-, ++, -+) quadrant layout instead. 

In addition, the axes in the graphic are not labeled, so the graphic itself can't even _be_ wrong. There is no "should" until we specify what the domain actually looks like: this graphic illustrates the parametric behaviour over time, not the curve's numeric identity in a known domain.
