### ISSUE TITLE
Licensing link at bottom of presentation version may be a 'dead link'

### ISSUE THREAD

**Issue by afarlie** [Pomax/BezierInfo-2#202]
I was reading the presentation version to find if there was a licensing statement. There is a link to  https://github.com/Pomax/bezierinfo/blob/gh-pages/LICENSE.md at the very bottom of the page at 
https://pomax.github.io/bezierinfo/. 

However this link appears to point to a page which no longer exists (perhaps due to restructuring of the repository)? 

Thanks for writing this book,  Please consider also if it's 'textbook' content that you could subimt to Wikibooks (http://en.wikibooks.org)

**Comment by Pomax** [comment]
Ah, thanks for the heads  up, looks like the LICENSE.md went missing on the page repo, but is still [on the dev repo](https://github.com/Pomax/BezierInfo-2/blob/master/LICENSE.md).

I'm currently working on a reliable way to generate the book "as book form", because right now it strongly relies on being interactive, and just "turning the page into a pdf" and then pretending that's a decent book is going to be a bad book.

Once I have the pdf (and probably epub) generation working, I'll be adding print on demand so that people who want a copy can order one for as low a cost as I can reasonably make it.
