### ISSUE TITLE
What programming language is function name(): ?

### ISSUE THREAD

**Issue by kiryph** [Pomax/BezierInfo-2#269]
https://github.com/Pomax/BezierInfo-2/blob/dda4808a34284342eb9278e14c8cc862dec81a03/docs/chapters/flattening/content.en-GB.md#L26-L32

In particular the syntax `function flattenCurve():` seems to be a mixture from Javascript and Python

https://en.wikipedia.org/wiki/Colon_(punctuation)#Programming_languages

https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(basic_instructions)#Functions

**Comment by Pomax** [comment]
it's a modernized pseudocode. You won't be able to copy-paste it into any existing language, but you _will_ be able to adapt it for any of them with barely any effort.

I'll add a note to explain that the code you'll be given is not copy-paste. (The primer isn't a quick stop for code =)

https://github.com/Pomax/BezierInfo-2/issues/270

**Comment by kiryph** [comment]
Thanks for the clarification. I was doubting myself but I was also already suspecting that this is meant to be pseudocode. However, I do not know what "modernized" pseudocode is.

IMHO the semi-colons could be removed. They are used inconsistently anyway. This is valid in JavaScript but encourages bad coding style. I think encouraging bad coding style is something "close-to-real" pseudocode should not do.

BTW A copy-paste from these snippets, even when it is valid syntax in one language, does not work since `curve` and other objects are never introduced in the primer.

If you want to encourage people to code it on their own, I would stick to conventional pseudocode and not a close-to-real code: in the current situation people still copy it and try to fiddle around until it works. Fiddling around here means people do not think about the algorithm but the syntax errors to resolve.
Some people convert code snippets to pictures or certain symbols to typographic equivalents, e.g.`"string"` to `“string”`, to prohibit copy-and-paste. However, I think this is overkill. Using pseudo-code (not close to real code) does this as well.

**Comment by Pomax** [comment]
the semicolons are a fair point, either everything should use it, or nothing should (though on a side note, semicolons in JS are absolutely required because ASI was only ever a hack. Use them in JS, obviously don't use them in Python)

I personally find real pseudocode super annoying to read, because it's thoroughly grounded in the programming languages of the 70s, so I'm going to keep using something that looks more like the programming languages of today instead, but cleaning everything up to be consistent is of course worthwhile, and is still pending in https://github.com/Pomax/BezierInfo-2/issues/257
