### ISSUE TITLE
Circle example in Section 3 is plotted wrong

### ISSUE THREAD

**Issue by MarkZH** [Pomax/BezierInfo-2#29]
Two problems in the Section 3 circle example:
- The graph shows the circle being drawn clockwise when it should be anticlockwise.
- The caption for the circle figure switches the formulas for x and y

**Comment by Pomax** [comment]
Super late to getting to this issue, but: without labeled axes, neither of those can be shown true =)

Labeling the axes was intentional, exactly to avoid this; there is no clock direction until the coordinate system is known, and different technologies use different conventions. In math class, you usually set them to be (0,0) at the center, with quadrants (-,+) in the upper left, (-,-) lower left, (+,+) upper right, and (+,-) lower right. That is almost universally not how computer graphics work, where (0,0) is in the upper left, negatives are to the top and left, and positives are to the right and down.
