### ISSUE TITLE
Distance from curve to vector 

### ISSUE THREAD

**Issue by ghpabs** [Pomax/BezierInfo-2#30]
Is there a way to calculate the distance from the curve to a given x, y point?

**Comment by Pomax** [comment]
There is no "the distance": with an `n`th order curve there are infinitely many points (x,y) that lie at the same distance from from `n` points. For a quadratic curve you may find two points at the same distance from (x,y), rather than one; for cubic curves you may get three points, etc.

Solving this symbolically is expensive, so the cheap solution is to simply scan the curve in terms of distance (curvepoint(t))--(x,y) with steps of (t) that are small enough that the curve can't drastically change direction between two consecutive values. Then when you've found one or more good (t) values, do a fine check around them so you can find the local minimum near them (the odds that the initial (t) value was the true minimum are very small indeed)
