### ISSUE TITLE
A good approximation of t

### ISSUE THREAD

**Issue by luc4leone** [Pomax/BezierInfo-2#325]
[Section 31](https://pomax.github.io/bezierinfo/#pointcurves):

>we can just as easily approximate one by treating the distance between the `start` and `B` point, and `B` and `end` point as a ratio, using

![image](https://user-images.githubusercontent.com/2797254/131532623-6d8cde55-d95b-40c1-aa08-ae1ac974cfa4.png)

I don't understand why this ratio is a good approximation of `t`. If I understood correctly, geometrically `d1` and `d2` are these

<img src="https://user-images.githubusercontent.com/2797254/131532774-4d699bf6-eeba-44ae-943c-dea1f7049a21.png" width="400" />

and `t` is the ratio of, for example: `(v1 - start) / (green point - start)`

`v1 - start`: distance between `start` point and `v1` point
`green point - start`: distance between `green` point and `start` point

I don't "see it" geometrically why the approximation ratio should be similar to the real `t` ratio, @Pomax can you please explain it why instead it is, or maybe show me what I don't see?

**Comment by Pomax** [comment]
because for start-v1-green, that's _exactly_ what the the `t` value is: a `t` value of 0.3 means that the distance from start to v1 is 0.3 times the total distance, where the total distance is `start--v1` + `v1--green`, so:

```
t = || start--v1 || / || start--v1 + v1--green ||
```

Extending that to a curve rather than a line segment: rather than the _exact_ value, using that formula now gives us an _approximate_ value. The fancier the curve, the less good an approximation it'll be, but it gives us a value that's good enough for the purpose of constructing a curve "from nothing" (after all, we don't already "have" a curve, we're just inventing one to fit three points. There are infinitely many cubic curves through those points, so we just neeed _any_ reasonable `t` value out of the infinite number we could choose from)

**Comment by luc4leone** [comment]
ahh...I think I got it!

We know that: 

`B = u(t)*S + (1-u(t))*E`

We don't know `u(t)` so we use the formula for `t` **as if** `S-B-E`, instead of being a curve, it was a line. Did I understood it right @Pomax ?

---
PS


Is the above `B = u(t)*S + (1-u(t))*E` right? Shouldn't it be: `B = (1-u(t))*S + u(t)*E`

**Comment by Pomax** [comment]
correct, but for a given `t` value, it's always a `(1-t)` factor for the first point, and a `t` factor for the second point.

**Comment by luc4leone** [comment]
>...it's always a (1-t) factor for the first point, and a t factor for the second point.

Then, would this be right?

<img src="https://user-images.githubusercontent.com/2797254/131694671-58deb6b0-6901-45b1-a636-7d7e9e35506c.png" width="600" />

(ref. to [section 30](https://pomax.github.io/bezierinfo/#abc))

**Comment by Pomax** [comment]
Yes and no. No, because `u(t)` is not a t value, but yes because u(t) is symmetrical over 0.5 so technically `u(t)` and `u(1-t)` are the exact same value.

**Comment by Pomax** [comment]
No, note that `u(t)` is "some function of `t`", not itself a `t` value. While `t` is always between 0 and 1, `u(t)` is somewhere between 0 and positive infinity.
