### ISSUE TITLE
"Tight boxes" is wrong

### ISSUE THREAD

**Issue by behdad** [Pomax/BezierInfo-2#34]
You don't define what you mean by "tight".  I can only assume you mean box with smallest area.  In which case, the boxes you define are not tight. They are just parallel to the chord connecting the end points.

Here's, for a example, a quadratic that exposes the issue: (220,10), (20,250), (220,25)

Here's one for cubic: (110,145), (10,130), (220,130), (130,125)

**Comment by Pomax** [comment]
I don't. I just mean "tight". As per the article:

"These are, strictly speaking, not necessarily the tightest possible bounding boxes. It is possible to compute the optimal bounding box by determining which spanning lines we need to effect a minimal box area, but because of the parametric nature of Bézier curves this is actually a rather costly operation, and the gain in bounding precision is often not worth it. If there is high demand for it, I'll add a section on how to precisely compute the best fit bounding box, but the maths is fairly gruelling and just not really worth spending time on."

**Comment by behdad** [comment]
Ah, somehow I missed that.
