### ISSUE TITLE
PDF version available?

### ISSUE THREAD

**Issue by AllanLRH** [Pomax/BezierInfo-2#94]
This seems like a really good resource on bezier curves, but I'd really like a pdf-version, as I'm not a big fan of reading tons of text on a screen – does it exist, or are there any plans to create a pdf version?

**Comment by Pomax** [comment]
it does not, and there is not because the intereractive graphics won't work. But you can always just print it to your own PDF by telling your browser to print and then telling it to use whatever PDF printer driver you have (far as I know if you install acrobat or something you get a pdf printer installed "for free")

**Comment by Pomax** [comment]
that said the print media CSS has not been updated in a while, so that'll be worth fixing.

**Comment by AllanLRH** [comment]
Ok, and thanks for the quick reply 👍
